
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    chromium \
    chromium-driver \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENV PYTHONUNBUFFERED=1 \
    CHROME_EXECUTABLE_PATH=/usr/lib/chromium/chromium \
    CHROMEDRIVER_PATH=/usr/lib/chromium/chromedriver

CMD ["python", "main.py"]
