FROM apache/airflow:2.7.1-python3.9

WORKDIR /app

COPY requirements.txt .

USER root
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    chromium \
    chromium-driver \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1 \
    CHROME_EXECUTABLE_PATH=/usr/lib/chromium/chromium \
    CHROMEDRIVER_PATH=/usr/lib/chromium/chromedriver \
    AIRFLOW__CORE__LOAD_EXAMPLES=False
